{{- if .Values.secrets.gcpServiceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-ingestion.fullname" . }}-gcp-sa
  labels:
    {{- include "spark-ingestion.labels" . | nindent 4 }}
type: Opaque
data:
  key.json: {{ .Values.secrets.gcpServiceAccountKey | b64enc }}
{{- end }}
