apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-ingestion.fullname" . }}-spark-defaults
  labels:
    {{- include "spark-ingestion.labels" . | nindent 4 }}
data:
  spark-defaults.conf: |
    spark.kubernetes.namespace={{ .Values.spark.namespace }}
    spark.kubernetes.container.image={{ .Values.sparkImage.repository }}:{{ .Values.sparkImage.tag }}
    spark.kubernetes.authenticate.driver.serviceAccountName={{ .Values.spark.serviceAccount }}
    spark.driver.cores={{ .Values.spark.driverCores }}
    spark.driver.memory={{ .Values.spark.driverMemory }}
    spark.executor.cores={{ .Values.spark.executorCores }}
    spark.executor.memory={{ .Values.spark.executorMemory }}
    spark.executor.instances={{ .Values.spark.executorInstances }}
