apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.spark.serviceAccount }}
  namespace: {{ .Values.spark.namespace }}
  labels:
    {{- include "spark-ingestion.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spark-ingestion.fullname" . }}-spark-role
  namespace: {{ .Values.spark.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spark-ingestion.fullname" . }}-spark-rolebinding
  namespace: {{ .Values.spark.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.spark.serviceAccount }}
    namespace: {{ .Values.spark.namespace }}
roleRef:
  kind: Role
  name: {{ include "spark-ingestion.fullname" . }}-spark-role
  apiGroup: rbac.authorization.k8s.io
